version: 2

conda:
    environment: docs/environment.yml

sphinx:
   configuration: docs/conf.py

build:
   image: latest

python:
   version: 3.7
   install:
      - method: pip
        path: .
        
submodules:                                         
    include: all